name: patient-management-system

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    networks:
      - internal
    volumes:
      - kafka_data:/var/lib/kafka/data

  # --- PATIENT SERVICE ---
  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    platform: linux/arm64
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal
    depends_on:
      patient-service-db:
        condition: service_healthy

  # --- PATIENT DATABASE ---
  patient-service-db:
    image: postgres:18-alpine
    container_name: patient-service-db
    platform: linux/arm64
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db_volumes/patient-service-db:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_user -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # --- AUTH SERVICE DATABASE ---
  auth-service-db:
    image: postgres:18-alpine
    container_name: auth-service-db
    platform: linux/arm64
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db_volumes/auth-service-db:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_user -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # --- BILLING SERVICE ---
  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    image: billing-service:latest
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

  # --- ANALYTICS SERVICE ---
  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    image: analytics-service:latest
    ports:
      - "4002:4002"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal

  # --- API GATEWAY SERVICE ---
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    image: api-gateway:latest
    ports:
      - "4004:4004"
    environment:
     - AUTH_SERVICE_URL=http://auth-service:4005
    networks:
      - internal
 # --- AUTH SERVICE ---
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    image: auth-service:latest
    platform: linux/arm64
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - JWT_SECRET=rKgEWlw/bX05JGzdSWU3gl8dJaKMtNStO/84Fws2Dz0
    depends_on:
      auth-service-db:
        condition: service_healthy
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  kafka_data:
    driver: local
